### ISSUE TITLE
Move from aws.signature to a sourced setenv file

### ISSUE THREAD

**Issue by abhaylidbe** [jtwalsh0/traffic_safety#1]
The current script uses aws.signature::use_credentials(), but it seems easier to use environment variables (directions found in the aws.signature github repo). Should .gitignore that file and source it from master_script.R

**Comment by jtwalsh0** [comment]
Done: https://github.com/jtwalsh0/traffic_safety/commit/8ec9a41644ee71f075b02b14c0b94efa4c778d65
